
# ColourScheme
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
live_config_reload = true

[window]
dynamic_title = true

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 5
y = 5

[shell]
program = "/bin/zsh"

[env]
term = "xterm-256color"

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
size = 10
offset.y = 1
