
# ColourScheme
[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[window]
dynamic_title = true

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 5
y = 5

[terminal.shell]
program = "/bin/zsh"

[env]
term = "xterm-256color"

[font]
normal = {family = "JetBrains Mono Nerd Font Mono", style = "Regular"}
size = 10
offset.y = 1
