
# ColourScheme
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
live_config_reload = true

[shell]
program = "/bin/bash"

[env]
term = "xterm-256color"

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
size = 10

